// ************************************************************************
// *
// *    File        : DETSB16.H
// *
// *    Description : Detection routines for SB16
// *
// *    Copyright (C) 1993 Otto Chrons
// *
// ************************************************************************

#ifndef __DEF_DETECTSB16
#define __DEF_DETECTSB16

#ifdef __cplusplus
extern "C" {
#endif

int cdecl detectSB16( SOUNDCARD *sCard );

#ifdef __cplusplus
}
#endif

#endif
