// ************************************************************************
// *
// *    File        : SDI_WSS.H
// *
// *    Description : Header for Windows Sound System SDI
// *
// *    Copyright (C) 1993 Otto Chrons
// *
// ************************************************************************

#ifndef __DEF_SDIWSS
#define __DEF_SDIWSS

#ifdef __cplusplus
extern "C" {
#endif

void cdecl SDI_WSS(void);

#ifdef __cplusplus
}
#endif

#endif
