// ************************************************************************
// *
// *    File        : SDI_SB16.H
// *
// *    Description : Header for SB16 SDI
// *
// *    Copyright (C) 1993 Otto Chrons
// *
// ************************************************************************

#ifndef __DEF_SDISB16
#define __DEF_SDISB16

#ifdef __cplusplus
extern "C" {
#endif

void cdecl SDI_SB16(void);

#ifdef __cplusplus
}
#endif

#endif
