// ************************************************************************
// *
// *    File        : SDI_ARIA.H
// *
// *    Description : Header for Aria SDI
// *
// *    Copyright (C) 1993 Otto Chrons
// *
// ************************************************************************

#ifndef __DEF_SDIARIA
#define __DEF_SDIARIA

#ifdef __cplusplus
extern "C" {
#endif

void cdecl SDI_ARIA(void);

#ifdef __cplusplus
}
#endif

#endif
