// ************************************************************************
// *
// *    File        : SDI_PAS.H
// *
// *    Description : Header for PAS SDI
// *
// *    Copyright (C) 1992 Otto Chrons
// *
// ************************************************************************

#ifndef __DEF_SDIPAS
#define __DEF_SDIPAS

#ifdef __cplusplus
extern "C" {
#endif

void cdecl SDI_PAS(void);

#ifdef __cplusplus
}
#endif

#endif
