// ************************************************************************
// *
// *    File        : SDI_SB.H
// *
// *    Description : Header for SB (Pro) specific routines in MCP
// *
// *    Copyright (C) 1992 Otto Chrons
// *
// ************************************************************************

#ifdef __cplusplus
extern "C" {
#endif

void cdecl SDI_SB(void);
void cdecl SDI_SBPro(void);

#ifdef __cplusplus
}
#endif
